### ISSUE TITLE
Error on use of n-ary operators in space-invaders.rkt example

### ISSUE THREAD

**Issue by bakgatviooldoos** [soegaard/urlang#35]
I am trying out `urlang` for the first time, and the space invaders example does not work when using n-ary versions of operators, such as `(<= x y z)`. Easy fix, although I thought I would mention it, since it might mean something changed since the program was first written (or perhaps I am just missing something).

**Comment by soegaard** [comment]
Thanks for the error report.

At some point, long time ago, using `<=` with multiple arguments compiled to
valid, but non-sensical JavaScript. The form `(<= 1 4 3)` compiled
to `1 <= 4 <= 3`. This is valid in JavaScript but evaluates to `true`...

This has since been corrected - but I missed that Space Invaders needed to be updated.

Thanks again - don't hesitate to write if you find other oddities.

The fix:
https://github.com/soegaard/urlang/commit/65de509f8266b347fd9ead27be65336489c74323

**Comment by bakgatviooldoos** [comment]
Awesome, thanks!
